

all: people bib

people:
	# To install aton2json:
	#    npm install -g aton
	#    cd /usr/local/lib/node_modules/aton/example/cli
	#    make
	aton2json -p people.aton > people.json


bib:
	aton2json -p bibliography.aton > bibliography.json
