repository: "pianoroll/SUPRA"

output: "web"
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: "SUPRA"
# this appears on the top navigation bar next to the home button

site_title: "SUPRA"
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)


# Sets the website to use local javascript/css only.
#local: "true"
local: "false"

company_name: "Stanford University"
# this appears in the footer


github_editme_path: "pianoroll/SUPRA/blob/gh-pages"
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname: 
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 3333
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

production_url: http://supra.stanford.edu/
BASE_PATH: http://supra.stanford.edu/

# Location of CSS files and fonts.
css: style

exclude:
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways


